version: '3.8'

services:
  nextjs:
    build:
      context: .
      args:
        TMDB_API_KEY: ${TMDB_API_KEY}
    ports:
      - "3000:3000"
    networks:
      - seenit-net
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - seenit-net

  grafana:
    image: grafana/grafana
    ports:
      - "3100:3000"
    networks:
      - seenit-net

networks:
  seenit-net:
    driver: bridge