name: CI Branch

on:
    push:
        branches-ignore:
            - main

jobs:
    test-and-pr:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci --legacy-peer-deps

            - name: Run lint
              run: npm run lint

            - name: Run tests
              run: npm run test

            - name: Create Pull Request to main
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: 'Automated tests passed, creating PR to main'
                  branch: ${{ github.ref_name }}-pr-to-main-${{ github.run_number }}
                  base: main
                  title: 'Auto PR: Merge `${{ github.ref_name }}` into main'
                  body: |
                      This PR was automatically created by CI after successful tests on branch `${{ github.ref_name }}`.
                  draft: false
                  labels: automated-pr